---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ include "hello-world-operator.serviceAccountName" . }}-clusterrole
rules:
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ include "hello-world-operator.serviceAccountName" . }}-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hello-world-operator.serviceAccountName" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "hello-world-operator.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace }}"